packages:
  - apps/*
  - libs/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - bcrypt
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild
  - sharp

peerDependencyRules:
  ignoreMissing:
    - dotenv
  allowedVersions:
    "@nestjs/core": "11"
    "@nestjs/common": "11"
    "@nestjs/typeorm": "11"
    "reflect-metadata": "*"
