packages:
  - apps/*
  - libs/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - bcrypt
  - better-sqlite3
  - electron
  - electron-winstaller
  - sharp
